version: 2
updates:
  # Python dependencies managed by uv
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "tay2501"
    assignees:
      - "tay2501"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      security-updates:
        patterns:
          - "cryptography"
          - "urllib3"
          - "requests"
          - "pyopenssl"
        update-types:
          - "security-update"
      core-dependencies:
        patterns:
          - "typer"
          - "rich"
          - "pyperclip"
          - "watchdog"
          - "structlog"
        update-types:
          - "minor"
          - "patch"
      dev-tools:
        patterns:
          - "pytest*"
          - "black"
          - "isort" 
          - "mypy"
          - "ruff"
          - "pre-commit"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "tay2501"
    assignees:
      - "tay2501"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"