name: Security Vulnerability Report
description: Report a security vulnerability (private disclosure)
title: "[SECURITY] "
labels: ["security", "vulnerability", "high-priority"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT SECURITY NOTICE
        
        **Please DO NOT include sensitive information in this public issue.**
        
        For serious security vulnerabilities, please contact us privately at:
        - **Email**: [security contact email]
        - **GitHub Security Advisory**: Use the "Security" tab to report privately
        
        Only use this template for non-sensitive security improvements or questions.

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Input validation bypass
        - Encryption/Cryptography issue
        - Code injection
        - Path traversal
        - Information disclosure
        - Dependency vulnerability
        - Configuration security
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      description: How severe do you consider this vulnerability?
      options:
        - Low - Minimal impact
        - Medium - Some impact on security
        - High - Significant security risk
        - Critical - Immediate risk to users
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue (avoid specific exploit details)
      placeholder: General description of the security concern...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker potentially achieve?
      placeholder: An attacker could potentially...
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions of String Multitool are affected?
      placeholder: e.g., All versions, v2.6.0 and later, etc.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the application is affected?
      options:
        - String transformation engine
        - Cryptography manager (RSA/AES)
        - Input/Output handling
        - Configuration system
        - TSV conversion
        - Daemon mode
        - Interactive mode
        - Build process
        - Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this issue?
      placeholder: This could be mitigated by...
    validations:
      required: false

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your understanding of responsible disclosure
      options:
        - label: I understand this is a public issue and have not included sensitive exploit details
          required: true
        - label: I will work with the maintainers to resolve this issue responsibly
          required: true
        - label: I will not publicly disclose specific exploit details until the issue is resolved
          required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other relevant information (no sensitive details)
      placeholder: Additional context that might be helpful...